name: pages

on:
  push:
    branches: [ '**' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ここで必要ならビルド（Vite等）。静的サイトなら省略し docs/ をそのまま出す
      # - run: npm ci && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs        # ← 公開したいディレクトリに合わせて変更

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # PRはそのまま（プレビュー可）、mainは本番、それ以外はプレビュー
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ github.ref != 'refs/heads/main' }}
