name: pages

on:
  push:
    branches: [ '**' ]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - run: npm ci && npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .        # ← 公開したいディレクトリに合わせて変更

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: preview
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: true
